#!/bin/sh

set -e

PREREQ="cryptroot"

prereqs()
{
    echo "$PREREQ"
}

case $1 in
prereqs)
    prereqs
    exit 0
    ;;
esac

. /usr/share/initramfs-tools/hook-functions

# Install curl binaries into initramfs.
# Busybox wget implementation has no support for https.
copy_exec /usr/bin/curl /bin
