#!/bin/sh

set -e

PREREQ=""

prereqs()
{
    echo "$PREREQ"
}

case $1 in
prereqs)
    prereqs
    exit 0
    ;;
esac

. /usr/share/initramfs-tools/hook-functions

# Cut-down helper script for udhcpc.
# Example scripts: http://git.busybox.net/busybox/tree/examples/udhcp
mkdir -p ${DESTDIR}/etc/udhcpc
cat >${DESTDIR}/etc/udhcpc/default.script << 'EOF'
#!/bin/sh

[ -n "$broadcast" ] && BROADCAST="broadcast $broadcast"
[ -n "$subnet" ] && NETMASK="/$subnet"

case "$1" in
    deconfig)
        ip addr flush $interface
        ;;

    renew|bound)
        ip addr add dev $interface $ip $NETMASK $BROADCAST

        if [ -n "$router" ] ; then
            ip route flush dev $interface
            metric=0
            for i in $router ; do
                ip route add default dev $interface via $i metric $((metric++)) 
            done
        fi

        rm -f /etc/resolv.conf
        [ -n "$domain" ] && echo search $domain >> /etc/resolv.conf
        for i in $dns ; do
            echo nameserver $i >> /etc/resolv.conf
        done
        ;;
esac

exit 0
EOF
chmod 755 ${DESTDIR}/etc/udhcpc/default.script

# sys-libs/glibc loads additional libraries reqired for domain name lookups dynamically,
# they doesn't get picked up by initramfs installation scripts. Let's include them manually.
# For more information, see https://wiki.gentoo.org/wiki/Custom_Initramfs#DNS
copy_exec /lib/arm-linux-gnueabihf/libnss_mdns4_minimal.so.2
copy_exec /lib/arm-linux-gnueabihf/libnss_dns.so.2
